"""empty message

Revision ID: 3039d7f36dff
Revises: 7368f4a6568f
Create Date: 2024-10-01 14:16:49.781215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3039d7f36dff'
down_revision = '7368f4a6568f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure', schema=None) as batch_op:
        batch_op.drop_column('hour')

    # ### end Alembic commands ###
