"""empty message

Revision ID: 7368f4a6568f
Revises: 6141aedc1d36
Create Date: 2024-10-01 13:54:47.992580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7368f4a6568f'
down_revision = '6141aedc1d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=240), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.Column('temperature', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measure')
    # ### end Alembic commands ###
