"""empty message

Revision ID: 85cf956131e7
Revises: 3039d7f36dff
Create Date: 2024-10-27 20:36:43.724400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cf956131e7'
down_revision = '3039d7f36dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('distance', sa.String(length=120), nullable=True))
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('distance')
        batch_op.drop_column('device')

    # ### end Alembic commands ###
